version: '3.8'

services:
  probly:
    build:
      context: .
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    restart: unless-stopped 